[package]
name = "polars_go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.46", features = ["csv", "polars-io", "lazy"] }
lazy_static = "1.5"
